# Generated by Django 2.2.16 on 2021-11-20 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20211119_1337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['year']},
        ),
    ]
